CUDA_VISIBLE_DEVICES=0
Mon Jun  9 13:47:48 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.86.10              Driver Version: 570.86.10      CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA L40S                    Off |   00000000:17:00.0 Off |                    0 |
| N/A   29C    P8             32W /  350W |       1MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
Traceback (most recent call last):
  File "/home/guests/apesare/SpeedE/run_experiments.py", line 169, in <module>
    main(**dict(arg.split('=') for arg in sys.argv[1:]))  # kwargs
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guests/apesare/SpeedE/run_experiments.py", line 127, in main
    pipeline(
  File "/home/guests/apesare/SpeedE/venv/lib/python3.12/site-packages/pykeen/pipeline/api.py", line 1492, in pipeline
    training, testing, validation = _handle_dataset(
                                    ^^^^^^^^^^^^^^^^
  File "/home/guests/apesare/SpeedE/venv/lib/python3.12/site-packages/pykeen/pipeline/api.py", line 890, in _handle_dataset
    dataset_instance: Dataset = get_dataset(
                                ^^^^^^^^^^^^
  File "/home/guests/apesare/SpeedE/venv/lib/python3.12/site-packages/pykeen/datasets/utils.py", line 136, in get_dataset
    return _cached_get_dataset(dataset, dataset_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guests/apesare/SpeedE/venv/lib/python3.12/site-packages/pykeen/datasets/utils.py", line 223, in _cached_get_dataset
    dataset_cls.from_directory_binary(path),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guests/apesare/SpeedE/venv/lib/python3.12/site-packages/pykeen/datasets/base.py", line 259, in from_directory_binary
    tfs[key] = cls.triples_factory_cls.from_path_binary(path=tf_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guests/apesare/SpeedE/venv/lib/python3.12/site-packages/pykeen/triples/triples_factory.py", line 732, in from_path_binary
    return cls(**cls._from_path_binary(path=path))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guests/apesare/SpeedE/venv/lib/python3.12/site-packages/pykeen/triples/triples_factory.py", line 1023, in _from_path_binary
    data = super()._from_path_binary(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guests/apesare/SpeedE/venv/lib/python3.12/site-packages/pykeen/triples/triples_factory.py", line 740, in _from_path_binary
    data = dict(torch.load(path.joinpath(cls.base_file_name)))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guests/apesare/SpeedE/venv/lib/python3.12/site-packages/torch/serialization.py", line 1524, in load
    raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
_pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, [1mdo those steps only if you trust the source of the checkpoint[0m. 
	(1) In PyTorch 2.6, we changed the default value of the `weights_only` argument in `torch.load` from `False` to `True`. Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
	(2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
	WeightsUnpickler error: Unsupported global: GLOBAL pathlib.PosixPath was not an allowed global by default. Please use `torch.serialization.add_safe_globals([pathlib.PosixPath])` or the `torch.serialization.safe_globals([pathlib.PosixPath])` context manager to allowlist this global if you trust this class/function.

Check the documentation of torch.load to learn more about types accepted by default with weights_only https://pytorch.org/docs/stable/generated/torch.load.html.
